### PR TITLE
Support REST API v0.6, fixes and updates.

### LINKED ISSUE #6: Issue during copying file to custom s3 storage
http://stackoverflow.com/questions/28776196/uploadcare-having-trouble-using-java-library-to-copy-files-from-uploadcare-stor/

### LINKED ISSUE #27: Add support for new params in copyFile
There are several optional params for local and remote file copy methods.
We need to add support for those.

#26

### PR DESCRIPTION
**Pull request by raphaelnew**
Fixes #27 #26 #19 #25 #24 #23 #21 #20 #14 , #6 
Properly Implements features requested in PR #22 and #15 

## Description

**Added**
- Update **uploadcare-java** library to v3.3.0
- Support Uploadcare REST API v0.6
- File: Add new fields
- Group: get list of groups with filter params. Create/Store group.
- Add support for batch store/delete calls for Files
- Add ability to use Client without "secret key" for: uploading file/get uploaded file info/creating group/get created group info.
- Add ability to do "Signed Uploads" when using FileUploader/UrlUploader/Create Group.
- Add ability to copy files in local/remote storage. Remove old copy file method. Add support for "CDN URL" as source for copy operations.
- Add multipart upload support for FileUploader.
- Add Webhooks support. Get Webhooks, Create/Update/Delete Webhook is supported.
- Update UrlUploader, add ability to specify additional params.

**Changed**
- Renamed "privateKey" variable to "secretKey".
- Default Client auth method now is HMAC-based instead of Simple Auth.
- Copy methods now return "CopyFile" class that contain the new copied instance of the file/url ready to be used.

**Fixed**
- Uploaded files now has proper MimeType.
- "InputStream" content uploading.
- UrlUploader correctly handle "progress", "waiting", "unknown" statuses of a file uploaded from URL. Do exponential backoff and throw error instead of polling Upload API server indefinitely.

### CODE REVIEW

File: src/main/java/com/uploadcare/api/Client.java [hunk 1]
```diff
@@ -252,26 +571,113 @@ public void close() {
...
+     *
+     * @param fileId     Resource UUID
+     * @param store      The parameter only applies to the Uploadcare storage and MUST be either true or false.
+     * @param makePublic Applicable to custom storage only. MUST be either true or false. true to make copied files
+     *                   available via public links, false to reverse the behavior.
+     *
      * @return An object containing the results of the copy request
      */
-    public CopyFileData copyFile(String fileId, String storage) {
+    public CopyFileData copyFileLocalStorage(String fileId, Boolean store, Boolean makePublic) {
```
[the remark this answers is not in the document]
Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/Client.java:597]: Fixed in c584fc4c

File: src/main/java/com/uploadcare/api/FilesQueryBuilder.java [hunk 2]
```diff
@@ -63,12 +58,23 @@ public FilesQueryBuilder from(Date from) {
...
-     * Adds a filter for datetime to which objects will be returned.
+     * Specifies the way files are sorted.
      *
-     * @param to A uploading datetime to which objects will be returned.
+     * @param order [Order]
+     * @see com.uploadcare.urls.UrlParameter.Order
      */
-    public FilesQueryBuilder to(Date to) {
-        parameters.add(new FilesToParameter(to));
+    public FilesQueryBuilder ordering(UrlParameter.Order order){
```
[the remark this answers is not in the document]
Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/FilesQueryBuilder.java]: Updated in e70a2f29

File: src/main/java/com/uploadcare/api/RequestHelper.java [hunk 3]
```diff
@@ -25,88 +27,117 @@
...
+ * A helper class for doing API calls to the Uploadcare API. Supports API version 0.6.
  *
  * TODO Support of throttled requests needs to be added
  */
 public class RequestHelper {
 
     private final Client client;
 
-    public static final String LIBRARY_VERSION = "3.1";
+    public static final String LIBRARY_VERSION = "3.2.0";
```
[the remark this answers is not in the document]
Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/RequestHelper.java]: Fixed in 9ac2f131

File: src/main/java/com/uploadcare/data/FileData.java [hunk 4]
```diff
@@ -1,21 +1,49 @@
...
+                ", originalFilename='" + originalFilename + '\'' +
+                ", originalFileUrl=" + originalFileUrl +
+                ", datetimeUploaded=" + datetimeUploaded +
+                ", datetimeStored=" + datetimeStored +
+                ", datetimeRemoved=" + datetimeRemoved +
+                ", imageInfo=" + imageInfo +
+                ", videoInfo=" + videoInfo +
+                ", rekognitionInfo=" + rekognitionInfo +
+                ", variations=" + variations +
+                '}';
```
[the remark this answers is not in the document]
Comment (raphaelnew) [reply src/main/java/com/uploadcare/data/FileData.java]: Updated in a21c0413

File: src/main/java/com/uploadcare/data/GroupData.java [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+    public String toString() {
+        return "GroupData{" +
+                "id='" + id + '\'' +
+                ", url=" + url +
+                ", datetimeCreated=" + datetimeCreated +
+                ", datetimeStored=" + datetimeStored +
+                ", filesCount=" + filesCount +
+                ", cdnUrl=" + cdnUrl +
+                ", files=" + files +
+                '}';
```
[the remark this answers is not in the document]
Comment (raphaelnew) [reply src/main/java/com/uploadcare/data/GroupData.java]: Updated in a21c0413

**Comment by raphaelnew** [comment]
@dmitry-mukhin Resolved all issues provided in comments, couple other small related fixes/updates implemented during testing.

File: src/main/java/com/uploadcare/api/Client.java [hunk 6]
```diff
@@ -252,26 +571,126 @@ public void close() {
...
+     * @deprecated Use {@link #copyFileLocalStorage(String, Boolean, Boolean)}
+     * or {@link #copyFileRemoteStorage(String, String, Boolean, String)} instead.
+     *
      * @param fileId  Resource UUID
      * @param storage Target storage name
      * @return An object containing the results of the copy request
      */
+    @Deprecated
     public CopyFileData copyFile(String fileId, String storage) {
+        return copyFileRemoteStorage(fileId, storage, true, null);
```
Comment (dmitry-mukhin) [inline src/main/java/com/uploadcare/api/Client.java:583]: but what about local copy?
```suggestion
        if (storage != null && !storage.isEmpty()) {
            return copyFileRemoteStorage(fileId, storage, true, null);
        } else {
            return copyFileLocalStorage(fileId, true, true);
        }
```

File: src/main/java/com/uploadcare/api/Client.java [hunk 7]
```diff
@@ -252,26 +571,126 @@ public void close() {
...
     /**
+     * @deprecated Use {@link #copyFileLocalStorage(String, Boolean, Boolean)}
+     * or {@link #copyFileRemoteStorage(String, String, Boolean, String)} instead.
+     *
      * @param fileId  Resource UUID
      * @param storage Target storage name
      * @return An object containing the results of the copy request
      */
+    @Deprecated
     public CopyFileData copyFile(String fileId, String storage) {
```
Comment (dmitry-mukhin) [inline src/main/java/com/uploadcare/api/Client.java:582]: Do I understand correctly, that fileId can also be a URL here as it's being passed to API as is?

Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/Client.java:582]: No it's not supporting CDN URL, only UUID of a file is supported.

Comment (dmitry-mukhin) [reply src/main/java/com/uploadcare/api/Client.java:582]: I believe that I see that a string is being passed over the network. It can contain both UUID or URL. This is supported by API, and should be supported by the lib.

Am I incorrect? E.g. you can't pass an Uploadcare CDN URL in `fileId` param?

Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/Client.java]: @dmitry-mukhin you are right, Solved in 79b3a804. I've added possibility to provide "CDN URL" as copy source in all copy methods local/external, updated comments, and Updated the returned result to contain the new copied instance of the file/url ready to be used according to latest docs. Tested.

**Comment by raphaelnew** [comment]
79b3a804 commit fixes issue described in #6 , tested.

File: src/main/java/com/uploadcare/api/Client.java [hunk 8]
```diff
@@ -252,26 +567,135 @@ public void close() {
...
+    }
+
+    /**
+     * Copy file to local storage. Copy original files or their modified versions to default storage. Source files MAY
+     * either be stored or just uploaded and MUST NOT be deleted.
+     *
+     * @param source     File Resource UUID or A CDN URL.
+     * @param store      The parameter only applies to the Uploadcare storage and MUST be either true or false.
+     * @param makePublic Applicable to custom storage only. MUST be either true or false. true to make copied files
+     *                   available via public links, false to reverse the behavior.
```
Comment (dmitry-mukhin) [inline src/main/java/com/uploadcare/api/Client.java:594]:
```suggestion
     * @param store      The parameter only applies to the Uploadcare storage and MUST be either true or false.
```

File: src/main/java/com/uploadcare/api/Client.java [hunk 9]
```diff
@@ -252,26 +567,135 @@ public void close() {
...
+     *
      * @return An object containing the results of the copy request
      */
-    public CopyFileData copyFile(String fileId, String storage) {
+    public CopyFile copyFileLocalStorage(String source, Boolean store, Boolean makePublic) {
+        CopyOptionsData copyOptionsData = new CopyOptionsData();
+        copyOptionsData.source = source;
+        copyOptionsData.store = store;
+        copyOptionsData.makePublic = makePublic;
```
Comment (dmitry-mukhin) [inline src/main/java/com/uploadcare/api/Client.java:602]: this does not make sense
```suggestion
    public CopyFile copyFileLocalStorage(String source, Boolean store) {
        CopyOptionsData copyOptionsData = new CopyOptionsData();
        copyOptionsData.source = source;
        copyOptionsData.store = store;
```

File: src/main/java/com/uploadcare/api/Client.java (hunk 8 above)
Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/Client.java:594]: @dmitry-mukhin  https://uploadcare.com/api-refs/rest-api/v0.6.0/#operation/copyFileLocal

Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/Client.java]: Fixed in 33471478

File: src/main/java/com/uploadcare/api/Client.java (hunk 9 above)
Comment (raphaelnew) [reply src/main/java/com/uploadcare/api/Client.java]: Fixed in 33471478
